"""Turn Tyrbot's mmdb.txt (text.mdb extraction) into MmdbData.cs.

    python gen_mmdb.py <path-to-mmdb.txt> <path-to-MmdbData.cs>

mmdb.txt lines are Python literals: [category, instance, "template"]. The templates carry
printf-style placeholders (%s, %d, %u, %i, %02d, %02u) that the '~&' ext-message params fill in.
Everything is embedded in code so the clientless bot never needs the game's text database.
"""
import ast
import sys

HEADER = """\
// <auto-generated>
// Message templates for AO's '~&' ext messages (system feedback lines), embedded in code so the
// clientless bot never touches the game's text database or ldb.dll's RemoteFormat::ParseString.
// Source: Tyrbot docs/mmdb.txt (text.mdb extracted 18-May-2018). {count} templates, {cats} categories.
// Regenerate: python tools/mmdb-import/gen_mmdb.py <mmdb.txt> <MmdbData.cs>
// </auto-generated>
"""


def cs_escape(text):
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif 0x20 <= ord(ch) <= 0x7E:
            out.append(ch)
        else:
            out.append("\\u{0:04x}".format(ord(ch)))
    return "".join(out)


def main():
    src, dst = sys.argv[1], sys.argv[2]
    entries = {}
    for line in open(src, encoding="utf-8"):
        line = line.strip()
        if not line.startswith("["):
            continue
        cat, inst, template = ast.literal_eval(line)
        entries.setdefault(cat, []).append((inst, template))

    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER.format(count=sum(len(v) for v in entries.values()), cats=len(entries)))
        f.write("namespace SmokeLounge.AOtomation.Messaging;\n\n")
        f.write("public static class MmdbData\n{\n")
        f.write("    public static readonly IReadOnlyDictionary<int, IReadOnlyDictionary<int, string>> Categories =\n")
        f.write("        new Dictionary<int, IReadOnlyDictionary<int, string>>\n        {\n")
        for cat in sorted(entries):
            f.write("            [{0}] = new Dictionary<int, string>\n            {{\n".format(cat))
            for inst, template in entries[cat]:
                f.write('                [{0}] = "{1}",\n'.format(inst, cs_escape(template)))
            f.write("            },\n")
        f.write("        };\n\n")
        f.write("""\
    public static bool TryGet(int category, int instance, out string template)
    {
        template = null;
        return Categories.TryGetValue(category, out var instances) && instances.TryGetValue(instance, out template);
    }
}
""")
    print("wrote {0}: {1} templates in {2} categories".format(dst, sum(len(v) for v in entries.values()), len(entries)))


if __name__ == "__main__":
    main()
