<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>AOSharp.Clientless.Common</RootNamespace>
        <AssemblyName>AOSharp.Clientless.Common</AssemblyName>
    </PropertyGroup>

</Project>
